#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
    path: /accueil
    controller: App\Controller\ConnexionController::index

connecter:
    path: /connecter
    controller: App\Controller\ConnexionController::connecter

deconnecter:
    path: /deconnecter
    controller: App\Controller\ConnexionController::deconnexion

comptable:
    path: /comptable
    controller: App\Controller\ComptableController::index

validerUneFiche:
    path: /comptable/valider
    controller: App\Controller\ComptableController::validerUneFiche

suivreUneFiche:
    path: /comptable/suivre
    controller: App\Controller\ComptableController::suivreUneFiche