#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
    path: /accueil
    controller: App\Controller\ConnexionController::index

connecter:
    path: /connecter
    controller: App\Controller\ConnexionController::connecter
